### ISSUE TITLE
Coming into problem while re-producing

### ISSUE THREAD

**Issue by ZacharyChenpk** [mjhosseini/open_contextual_link_pred#1]
Hello!
When I tried to re-produce this paper, with data downloaded by scripts/data.sh and existing pre-trained models by scripts/dl_pretrained.sh, I ran modeling/run_contextual_link_pred.py for training, but caught the error:

> ....... (about 650k lines)
> batch with types, offset:  internet#internet 21304
> flushing batch with size: 8
> max_len:  40
> /home/chenzhb/anaconda3/envs/torch/lib/python3.8/site-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
>   warnings.warn('Was asked to gather along dimension 0, but all '
> current batch size: 8
> eval step: 0
> writing to eval_file
> eval_eval_acc 0.9151376146788991 8
> eval_eval_loss 0.32982179522514343 8
> eval_eval_AP 0.7643083259611874 8
> 07/04/2022 07:40:13 - INFO - __main__ -   ***** Evaluating Entailmet Scores  *****
> 07/04/2022 07:40:13 - INFO - __main__ -     Batch size = 1024
> batch with types, offset:  internet#software 21413
> flushing batch with size: 57
> max_len:  40
> /home/chenzhb/anaconda3/envs/torch/lib/python3.8/site-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
>   warnings.warn('Was asked to gather along dimension 0, but all '
> current batch size: 57
> eval step: 0
> writing to eval_file
> eval_eval_acc 0.6990131578947368 57
> eval_eval_loss 1.6767184734344482 57
> eval_eval_AP 0.4460657609508438 57
> 07/04/2022 07:40:14 - INFO - __main__ -   ***** Evaluating Entailmet Scores  *****
> 07/04/2022 07:40:14 - INFO - __main__ -     Batch size = 1024
> batch with types, offset:  internet#time 21445
> flushing batch with size: 21
> max_len:  40
> /home/chenzhb/anaconda3/envs/torch/lib/python3.8/site-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
>   warnings.warn('Was asked to gather along dimension 0, but all '
> current batch size: 21
> eval step: 0
> writing to eval_file
> eval_eval_acc 0.9715447154471545 21
> eval_eval_loss 0.22238266468048096 21
> eval_eval_AP 0.8452657562099761 21
> 07/04/2022 07:40:15 - INFO - __main__ -   ***** Evaluating Entailmet Scores  *****
> 07/04/2022 07:40:15 - INFO - __main__ -     Batch size = 1024
> batch with types, offset:  internet#title 21527
> flushing batch with size: 23
> max_len:  40
> /home/chenzhb/anaconda3/envs/torch/lib/python3.8/site-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
>   warnings.warn('Was asked to gather along dimension 0, but all '
> current batch size: 23
> eval step: 0
> writing to eval_file
> eval_eval_acc 0.8439359267734554 23
> eval_eval_loss 0.5056710243225098 23
> eval_eval_AP 0.6505928182743316 23
> 07/04/2022 07:40:17 - INFO - __main__ -   ***** Evaluating Entailmet Scores  *****
> 07/04/2022 07:40:17 - INFO - __main__ -     Batch size = 1024
> batch with types, offset:  language#location 21633
> flushing batch with size: 3
> max_len:  40
> /home/chenzhb/anaconda3/envs/torch/lib/python3.8/site-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
>   warnings.warn('Was asked to gather along dimension 0, but all '
> current batch size: 3
> eval step: 0
> writing to eval_file
> eval_eval_acc 0.9074074074074074 3
> eval_eval_loss 0.4855599105358124 3
> eval_eval_AP 0.8809523809523809 3
> 07/04/2022 07:40:18 - INFO - __main__ -   ***** Evaluating Entailmet Scores  *****
> 07/04/2022 07:40:18 - INFO - __main__ -     Batch size = 1024
> batch with types, offset:  living_thing#time 21694
> flushing batch with size: 12
> max_len:  40
> /home/chenzhb/anaconda3/envs/torch/lib/python3.8/site-packages/torch/nn/parallel/_functions.py:68: UserWarning: Was asked to gather along dimension 0, but all input tensors were scalars; will instead unsqueeze and return a vector.
>   warnings.warn('Was asked to gather along dimension 0, but all '
> current batch size: 12
> eval step: 0
> writing to eval_file
> eval_eval_acc 0.9322916666666666 12
> eval_eval_loss 1.4050407409667969 12
> eval_eval_AP 0.8262896825396826 12
> 07/04/2022 07:40:19 - INFO - __main__ -   ***** Evaluating Entailmet Scores  *****
> 07/04/2022 07:40:19 - INFO - __main__ -     Batch size = 1024
> batch with types, offset:  livingthing#building 21710
> flushing batch with size: 46
> Traceback (most recent call last):
>   File "modeling/run_contextual_link_pred.py", line 1081, in <module>
>     main()
>   File "modeling/run_contextual_link_pred.py", line 1037, in main
>     results, iter_eval_dataloader, eval_dataset = evaluate(args, model, iter_eval_dataloader, eval_dataset,
>   File "modeling/run_contextual_link_pred.py", line 81, in evaluate
>     batch_orig = next(iter_eval_dataloader)
>   File "/home/chenzhb/anaconda3/envs/torch/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
>     data = self._next_data()
>   File "/home/chenzhb/anaconda3/envs/torch/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 561, in _next_data
>     data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
>   File "/home/chenzhb/anaconda3/envs/torch/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 28, in fetch
>     data.append(next(self.dataset_iter))
>   File "/home/chenzhb/open_contextual_link_pred/modeling/utils_contextual_link_pred.py", line 437, in __iter__
>     self.prepare_batch(this_examples_extended, this_gr_idx)
>   File "/home/chenzhb/open_contextual_link_pred/modeling/utils_contextual_link_pred.py", line 583, in prepare_batch
>     assert num_neg_labels >= 0
> AssertionError

What should I do to fix the problem? It seems that something wrongly happened in data processing of testing?
By the way, uploading the final generated entailment graphs might be good for other researchers.

**Comment by mjhosseini** [comment]
Hi Zhibin,

Thanks for your interest in the paper. Something is going wrong when the code is trying to build some batches for evaluation. Could you please write here the exact command line(s) you tried to run? This way, I hope that I can replicate the error and find the issue (I couldn't replicate the error myself).

And thanks for the suggestion. I'll find a way to upload the final entailment graphs.

Best Regards,
Javad

**Comment by ZacharyChenpk** [comment]
I find the error log in run_contextual_link_pred.log. The command lines should be:

```
git clone https://github.com/mjhosseini/open_contextual_link_pred.git
cd open_contextual_link_pred/
sh scripts/requirements.sh
sh scripts/data.sh
sh scripts/dl_pretrained.sh
nohup python -u modeling/run_contextual_link_pred.py --model_type bert --model_name_or_path models/CNCE_lr_5e-4_ctx_lr_ratio_1e-2_bsz_64_entity_pair_split/checkpoint-631000  --do_test --do_lower_case --input_path data/news_bert_input.json --trels_folder data/typed_rels --all_triples_path data/NS_epair_split/ --max_seq_length 40 --per_gpu_batch_size=256 --cache_dir . --preferred_num_labels 100000 > run_contextual_link_pred.log 2>&1 &
```

Because of my proxy setting on the machine, I cannot achieve Google Drive automatically, so I downloaded and renamed the data and pretrained model from https://drive.google.com/uc?export=download&id=1lGqeBUL2JKlAclvsqNfwwR9NB6wl5uEH and  https://drive.google.com/uc?export=download&id=1VdeY62BjWS4bERKU-v-nnEu96IzjedQL respectively. 
I have checked the renamed path and ensure that they are right.

**Comment by mjhosseini** [comment]
I see, thanks! Could you add --evaluate_during_training and try again? If this doesn't fix the issue, could you add these lines above here and share the results?

https://github.com/mjhosseini/open_contextual_link_pred/blob/main/modeling/utils_contextual_link_pred.py#L583

if num_neg_labels < 0:
  print('num_labels: ', num_labels)
  print('all_pos_labels: ', all_pos_labels)

**Comment by ZacharyChenpk** [comment]
I have tried to add --evaluate_during_training, but unfortunately, it doesn't fix the issue. With BOTH the command argument and added three lines, the error log is as below:

> 07/11/2022 12:26:22 - INFO - __main__ -   ***** Evaluating Entailmet Scores  *****
> 07/11/2022 12:26:22 - INFO - __main__ -     Batch size = 256
> batch with types, offset:  living_thing#time 21694
> flushing batch with size: 12
> max_len:  40
> current batch size: 12
> eval step: 0
> writing to eval_file
> eval_eval_acc 0.9375 12
> eval_eval_loss 1.386428713798523 12
> eval_eval_AP 0.8262896825396826 12
> 07/11/2022 12:26:22 - INFO - __main__ -   ***** Evaluating Entailmet Scores  *****
> 07/11/2022 12:26:22 - INFO - __main__ -     Batch size = 256
> batch with types, offset:  livingthing#building 21710
> flushing batch with size: 46
> num_labels:  2
> all_pos_labels:  {33, 2, 4, 8, 9, 75, 55, 25, 29}
> Traceback (most recent call last):
>   File "modeling/run_contextual_link_pred.py", line 1081, in <module>
>     main()
>   File "modeling/run_contextual_link_pred.py", line 1037, in main
>     results, iter_eval_dataloader, eval_dataset = evaluate(args, model, iter_eval_dataloader, eval_dataset,
>   File "modeling/run_contextual_link_pred.py", line 81, in evaluate
>     batch_orig = next(iter_eval_dataloader)
>   File "/home/chenzhb/anaconda3/envs/torch/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
>     data = self._next_data()
>   File "/home/chenzhb/anaconda3/envs/torch/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 561, in _next_data
>     data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
>   File "/home/chenzhb/anaconda3/envs/torch/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 28, in fetch
>     data.append(next(self.dataset_iter))
>   File "/home/chenzhb/open_contextual_link_pred/modeling/utils_contextual_link_pred.py", line 437, in __iter__
>     self.prepare_batch(this_examples_extended, this_gr_idx)
>   File "/home/chenzhb/open_contextual_link_pred/modeling/utils_contextual_link_pred.py", line 586, in prepare_batch
>     assert num_neg_labels >= 0
> AssertionError

Maybe you need:

> num_labels:  2
> all_pos_labels:  {33, 2, 4, 8, 9, 75, 55, 25, 29}

It seems that something wrongly happened in graph livingthing#building?

**Comment by mjhosseini** [comment]
Thanks for your message. I realized there was an inconsistency between some files in the data folder (basically the relations folder containing *_trels.txt had graph indices inconsistent with the ones in news_bert_input.json). I've now fixed the data folder. Could you please download the folder again (using the updated data.sh script)? This should hopefully resolve the issue.

**Comment by mjhosseini** [comment]
I also uploaded the final entailment graphs. Please see the link on the main page.

**Comment by ZacharyChenpk** [comment]
The new data folder seems to work well. Thanks!

**Comment by mjhosseini** [comment]
Thank you, Zhibin, for bringing this issue to my attention!
